name: settle_up_trips
description: A new super project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ^3.1.1

dependencies:
  intl: ^0.17.0
  flutter:
    sdk: flutter

  english_words: ^4.0.0
  provider: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  # fonts:
    # - family: Oswald
    #   fonts:
        # - asset: fonts/Oswald-Regular.ttf
        # - asset: fonts/Oswald-Bold.ttf
        # - asset: fonts/Oswald-ExtraLight.ttf
        # - asset: fonts/Oswald-Light.ttf
        # - asset: fonts/Oswald-Medium.ttf
        # - asset: fonts/Oswald-SemiBold.ttf